modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = '''
${description}
'''

[[mixins]]
config = "titan_satellite.mixins.json"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
