modLoader = "javafml"
loaderVersion = "[4,)"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = '''
${description}
'''

[[mixins]]
config = "titan_moon.mixins.json"

[[dependencies.titan_moon]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.titan_moon]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

# 饰品前置（Curios）：本模组饰品依赖 Curios API，必需
[[dependencies.titan_moon]]
modId = "curios"
type = "required"
versionRange = "[9.2,)"
ordering = "AFTER"
side = "BOTH"

# GeckoLib 前置（实体动画）：甲烷微浮群的模型/动画渲染依赖，必需
[[dependencies.titan_moon]]
modId = "geckolib"
type = "required"
versionRange = "[4.7,)"
ordering = "AFTER"
side = "BOTH"

# 可选前置（联动配方用；缺省不影响加载）
[[dependencies.titan_moon]]
modId = "create"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.titan_moon]]
modId = "mekanism"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.titan_moon]]
modId = "farmersdelight"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
